# This is a basic workflow to help you get started with Actions

name: Action 3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: ${{ github.repository_owner == 'Mohammad-Sadra-Najafi' }}
    runs-on: android-latest
    name: Android
    steps:
      - name: "Android"
        uses: actions/github-script@v6
        with:
          script: |
            // Copied from .github/extract-pr-and-workflow-id.js
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            for (const artifact of allArtifacts.data.artifacts) {
              // Extract the PR number from the artifact name
              const match = /^npm-package-(.+)-(\d+)$/.exec(artifact.name);
              if (match) {
                const packageName = match[1].toUpperCase();
                require("fs").appendFileSync(
                  process.env.GITHUB_ENV,
                  `\nWORKFLOW_RUN_PR_FOR_${packageName}=${match[2]}` +
                    `\nWORKFLOW_RUN_ID_FOR_${packageName}=${context.payload.workflow_run.id}`
                );
              }
            }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
