name: dependant

on: push

jobs:
  ubunta:
    runs-on: ubunta-latest
    steps:
      - run: date
windows:
  needs: [ macos ]
  runs-on: windows-latest
  steps:
    - run: date
macos:
  runs-on: macos-latest
  steps:
    - run: date
depends:
  needs: [ ubunta, windows, macos ]
  runs-on: macos-latest
  steps:
    - run: date

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
      
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
